### ISSUE TITLE
Ionic Native SQLite plugin example not present

### ISSUE THREAD

**Issue by tcrespog** [smichelotti/Ionic2Course#1]
Hi, 
First of all I want to thank you for the high quality course you've made at Pluralsight.

In the SQLite section of the [README.md](https://github.com/smichelotti/Ionic2Course/blob/master/README.md#sqlite) file it's stated that the [`user-settings.service.ts`](https://github.com/smichelotti/Ionic2Course/blob/master/sql-storage/user-settings.service.ts) file has been updated in order to show an example of native SQLite plugin manipulation. However, the plugin doesn't seem to be used inside the file.
Am I missing something?

**Comment by smichelotti** [comment]
Yes, it's being used. Check out the import on line #4:

```
import { SQLite } from 'ionic-native';
```

Don't be confused that it's referencing `ionic-native`. Ionic Native is using these plugins under the covers. So this won't work **unless** you make sure to add the SQLite plugin to your project. That was the part you were missing.

**Comment by tcrespog** [comment]
I thought the plugin had to be used directly as in the examples present at https://ionicframework.com/docs/v2/native/sqlite. Now I see that it's used under the covers.
Thank you.
