### ISSUE TITLE
Getting all items from local storage 

### ISSUE THREAD

**Issue by dalenguyen** [smichelotti/Ionic2Course#11]
This is from Ionic Local Storage session. The getting all items from local storage has changed. 

```
let items = [];

this.storage.forEach(value => {
    items.push(JSON.parse(value));
})

return items.length ? items: null;
```
However, the forEach will return a Promise, so items will be empty and cannot be returned. How can you resolve this? 

Thanks,

**Comment by smichelotti** [comment]
Check the latest code in this repository located [here](http://cdn.stevemichelotti.com/code/elite-schedule-3.13.2.zip).  Full method that includes either local storage or Sqlite storage now looks like this:
```

getAllFavorites() : Promise<any[]> {
    if (this.sqlMode) {
      return this.sql.getAll();
    } else {
      return new Promise(resolve => {
        let results = [];
        this.storage.forEach(data => {
          console.log('***inside foreach', data);
          results.push(JSON.parse(data));
        });
        return resolve(results);
      });
    }
  }
```
