### ISSUE TITLE
JSON Firebase upload

### ISSUE THREAD

**Issue by dark5eid83** [smichelotti/Ionic2Course#12]
Hello, 
In the "Setting up your Backend" video that is in the "Working with HTTP and Lifecycle Events" you late how to up load the JSON file to Firebase. However, my console looks different from yours and does not feature the upload option that you used. I've searched through the documentation but all the information I find references how to upload using a script.
Any help or resource you could point me towards in order to resolve this would be greatly appreciated.
Jason

**Comment by smichelotti** [comment]
The Firebase console has been updated since the course was originally recorded. But you can still accomplish the same tasks. In the Firebase console, just go to your database and select the "Import JSON" option. https://support.google.com/firebase/answer/6386780?hl=en
