### ISSUE TITLE
Ionic 2 Testing Configuration

### ISSUE THREAD

**Issue by sf1234** [smichelotti/Ionic2Course#3]
I am looking to setup ionic 2 test suite. but i am unable to set it up.
I am aware  of angular 2 having simple test configuration.
Can you please guide me in this regard.

**Comment by smichelotti** [comment]
Have a look at testing with Ionic 2 here: http://lathonez.github.io/2016/ionic-2-unit-testing/

**Comment by sf1234** [comment]
Thank you very much.
