### ISSUE TITLE
Ion-Title on Team Home not changing

### ISSUE THREAD

**Issue by BrettKoenig** [smichelotti/Ionic2Course#4]
Hello,

I'm having an issue where the team name being displayed in the ion-title is not updating on team-home.

Specifically this happens if I click on Team A go to the team detail, choose a specific game, and click on their opponent from the game page, instead of showing "Team B" at the top of the Team Home view, it still shows "Team A" However, all the other data loaded on to the Team Home page at that time is that of Team B. I compared my code on team-home.ts/html and game.ts/html to that of the finished app  in your repo and they look nearly identitical.

**Comment by smichelotti** [comment]
Are you still having this issue? Please check the latest code in the course repository: http://cdn.stevemichelotti.com/code/elite-schedule-app-3.2.1.zip
