### ISSUE TITLE
TS2349:Cannot invoke an expression whose type lacks a call signature. 

### ISSUE THREAD

**Issue by graysonkent** [smichelotti/Ionic2Course#5]
I got the following error while trying to build the new source: 

> Error:(36, 7) TS2349:Cannot invoke an expression whose type lacks a call signature. Type '(<TResult1 = {}, TResult2 = never>(onfulfilled?: (value: {}) => TResult1 | PromiseLike<TResult1>,...' has no compatible call signatures.

In reference to line 36 of of `app.module.ts` :

```
      this.userSettings.initStorage().then(() => {
        this.rootPage = MyTeamsPage;
        this.refreshFavorites();
        this.events.subscribe('favorites:changed', () => this.refreshFavorites());
      });
```
It looks like similar errors from the VScode project are being set to ignore. Is it safe to ignore this?

<hr/>

TypeScript: 3.10.10
Ionic Framework: 2.0.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.10.2
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by stevenknox** [comment]
Try updating line 81 in `user-settings.service.ts` to 

`return new Promise<void>(resolve => resolve());`

**Comment by smichelotti** [comment]
Also, you can check the latest code in the course repository here: http://cdn.stevemichelotti.com/code/elite-schedule-app-3.2.1.zip
