### ISSUE TITLE
Google maps guides are out of date.

### ISSUE THREAD

**Issue by zsunderlandafcu** [smichelotti/Ionic2Course#8]
Angular Google Maps has been updated. Import is now:
`
import {AgmCoreModule} from "@agm/core";
`
and html elements are:
`  <agm-map id="map" [latitude]="map.lat" [longitude]="map.lng" [zoom]="map.zoom">
    <agm-marker id="main-marker" [latitude]="map.lat" [longitude]="map.lng"></agm-marker>
  </agm-map>`

**Comment by smichelotti** [comment]
Code download for the course has been updated: http://cdn.stevemichelotti.com/code/elite-schedule-3.13.2.zip
